# fly.toml app configuration file generated for home-health-help on 2025-10-30T20:54:58-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'home-health-help'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
