# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    steps:
      # Step 1: Check out your repository's code so the runner can access it.
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up the flyctl command-line tool.
      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      # Step 3: Create the .env.local file from your GitHub secret
      # and then import the secrets into your Fly.io app.
      - name: Create and import secrets
        run: |
          echo "${{ secrets.FLY_ENV_FILE }}" > .env.local
          flyctl secrets set NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY

      # Step 4: Deploy your application to Fly.io.
      - name: Deploy application
        run: flyctl deploy
